version: '3'

services:

  keycloak:
    image: jboss/keycloak:4.5.0.Final
    restart: on-failure
    command:
    - "-b"
    - "0.0.0.0"
    - "-Dkeycloak.migration.action=import"
    - "-Dkeycloak.migration.provider=dir"
    - "-Dkeycloak.migration.dir=/keycloack/"
    - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
    - ./keycloack:/keycloack/
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=Keycloak2018
    - DB_VENDOR=postgres
    - DB_USER=admin
    - DB_PASSWORD=password
    - DB_ADDR=keycloak-db
    - DB_PORT=5432
    - DB_DATABASE=keycloakdb
    ports:
    - "8180:8080"
    depends_on:
    - keycloak-db

  keycloak-db:
    image: postgres:11
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloakdb
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: