server:
  servlet:
    context-path: /keycloack-app

keycloak:
  auth-server-url: http://localhost:8180/auth/
  resource: keycloack-app
  realm: keycloackApp
  public-client: true
  principal-attribute: preferred_username


spring.freemarker:
  request-context-attribute: rc